# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6ec968a1954da1bce0be8eedae7c9669f1cf52ffe34e6e8d77de803ad208400540a1ba5352c0b7be87c78585a14ac25c2278ca7132fd428ba2ca914b47c34a2

test:
  secret_key_base: a1d86d188ef446f777fa527508abdd4f67a84f80b93ac222dde57abefebb3c9b4f24219249de69167b22e89c964f73a597bc4537553d955bab8632a2425e3ecc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
